#! /bin/bash

# variables
BSPD="$HOME/.config/bspwm/bspwm.d"
get_color="$BSPD/get-color.sh"

# bspwm config
bspc monitor -d 1 2 3 4 5 

bspc config border_width         1
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color \#$($get_color on-surface-dim)
bspc config focused_border_color \#$($get_color accent)

bspc config swallow_first_click true
bspc config pointer_follows_focus false

# apply bspwm rules
source "$BSPD/rules.sh" 

# run autostart
source "$BSPD/autostart.sh"
